# Nama workflow yang akan tampil di tab Actions GitHub
name: Otomatisasi Panggilan API Microsoft

# Pemicu (trigger) kapan workflow ini akan berjalan
on:
  # 1. Memungkinkan Anda menjalankan manual dari tab Actions
  workflow_dispatch:

  # 2. Berjalan sesuai jadwal (menggunakan format CRON)
  schedule:
    # Jalankan setiap 6 jam sekali. (Menit 0, setiap jam ke-6)
    # Anda bisa mengubahnya, misal '0 */12 * * *' untuk setiap 12 jam.
    - cron: '0 */6 * * *'

permissions:
  contents: write
  
# Daftar pekerjaan yang akan dilakukan oleh workflow
jobs:
  run-api-script:
    # Menggunakan server virtual Ubuntu terbaru dari GitHub
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi secara berurutan
    steps:
      # Langkah 1: Mengunduh kode dari repository Anda
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Python versi 3.9
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Langkah 3: Menginstal library Python yang dibutuhkan
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Langkah 4: Menjalankan skrip Python
      - name: Run The Python Script
        # 'env' adalah cara kita memberikan GitHub Secrets ke skrip Python
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        # Ganti 'run.py' jika nama file Python Anda berbeda
        run: python run.py

      # Langkah 5: Menyimpan perubahan (refresh token baru) kembali ke repository
      - name: Commit and Push Updated Token
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Secret.txt
          # Hanya commit jika ada perubahan pada file Secret.txt
          if git diff --staged --quiet; then
            echo "Token tidak berubah, tidak ada yang perlu di-commit."
          else
            git commit -m "bot: Perbarui Microsoft Refresh Token"
            git push
          fi
